server:
  port: 8888

spring:
  cloud:
    config:
      name: config-service
      server:
        git:
          skip-ssl-validation: true
          uri: https://github.com/extend9305/spring-cloud.git
          search-paths: git-local-repo
